# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ação de Deploy Backend

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs: 
     
   build:
    runs-on: ubuntu-latest
    name: Ação que faz deploy hipotetico apos o PullRequest foi mergeado
    if: github.event.pull_request.merged == true
    
          
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm -v
    - run: echo indo fazer deploy?
